name: website preview deployment

on:
  push:
    branches: [Preview]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: sync
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.KEY }}
          source: "site/*"
          target: "/home/clients/793e7dadbc54f2acdbb0cadc4196e9b5/sites/preview.mouvementplus.ch"
          strip_components: 1